name: clearApp
description: clear application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.8.1
  smooth_star_rating: ^1.1.1
  intl: ^0.16.0
  rflutter_alert: ^1.0.3
  flutter_screenutil: ^2.3.1
  http: ^0.12.2
  logger: ^0.9.1
  async: ^2.3.0
  flutter_slidable: ^0.5.4
  date_format: ^1.0.8
  fluttertoast: ^7.0.1
  sleek_circular_slider: ^1.1.0
  modal_bottom_sheet: ^0.2.0+1
  flutter_form_builder: ^3.12.0
  sticky_grouped_list: ^0.3.0
  flutter_styled_toast: ^1.3.2
  progress_indicators: ^0.1.5
  md2_tab_indicator: ^1.0.2
  pull_to_refresh: ^1.6.1
  selection_menu: ^0.9.0
  jwt_decoder: ^1.0.1
  provider: ^4.3.1
  mobx: ^1.2.1
  flutter_mobx: ^1.0.0
  json_annotation: ^3.0.0
  data_connection_checker: ^0.3.4
  auto_size_text: ^2.1.0
  flutter_picker: ^1.1.5

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.2.0
  mobx_codegen: ^1.1.0+1

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/design_course/
    - assets/fitness_app/
    - assets/hotel/
    - assets/menu/
    - assets/logo/

  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 100
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
