class RacketCard {
  final String id;
  final String name;
  final String location;
  final String image;
  final String type;
  final String balance;
  final int weight;
  final bool isavailable;

  RacketCard({
    this.id,
    this.name,
    this.location,
    this.image,
    this.isavailable,
    this.balance,
    this.type,
    this.weight,
  });
}

List<RacketCard> testlist = [
  RacketCard(
    id: "1",
    name: "YONEX",
    location: "TEST1",
    image: 'assets/logo/yonex.png',
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: true,
  ),
  RacketCard(
    id: "2",
    name: "VICTOR",
    location: "TEST1",
    image: "assets/logo/victor.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: true,
  ),
  RacketCard(
    id: "3",
    name: "VICTOR",
    location: "TEST1",
    image: "assets/logo/victor.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: false,
  ),
  RacketCard(
    id: "4",
    name: "Earth",
    location: "TEST1",
    image: 'assets/logo/yonex.png',
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: false,
  ),
  RacketCard(
    id: "5",
    name: "Mercury",
    location: "TEST1",
    image: "assets/logo/yonex.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: false,
  ),
  RacketCard(
    id: "6",
    name: "Mercury",
    location: "TEST1",
    image: "assets/logo/yonex.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: true,
  ),
];

List<RacketCard> racketcardlist = [
  RacketCard(
    id: "1",
    name: "YONEX",
    location: "ASTROX 5FX",
    image: 'assets/logo/yonex.png',
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: true,
  ),
  RacketCard(
    id: "2",
    name: "VICTOR",
    location: "ARS-70FNA",
    image: "assets/logo/victor.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: true,
  ),
  RacketCard(
    id: "3",
    name: "VICTOR",
    location: "TK-70F",
    image: "assets/logo/victor.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: false,
  ),
  RacketCard(
    id: "4",
    name: "Earth",
    location: "VOLTRIC LD200",
    image: 'assets/logo/yonex.png',
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: false,
  ),
  RacketCard(
    id: "5",
    name: "Mercury",
    location: "NANORAY 800",
    image: "assets/logo/yonex.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: false,
  ),
  RacketCard(
    id: "6",
    name: "Mercury",
    location: "NANORAY 300",
    image: "assets/logo/yonex.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: true,
  ),
  RacketCard(
    id: "7",
    name: "Mercury",
    location: "VARS-80X C",
    image: "assets/logo/victor.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: false,
  ),
  RacketCard(
    id: "8",
    name: "Mercury",
    location: "ASTROX 100 ZX",
    image: "assets/logo/yonex.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: false,
  ),
  RacketCard(
    id: "9",
    name: "Mercury",
    location: "AURASPEED 90S",
    image: "assets/logo/victor.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: true,
  ),
  RacketCard(
    id: "10",
    name: "Mercury",
    location: "HYPERNANO 70",
    image: "assets/logo/victor.png",
    balance: 'Head heavy',
    type: 'Attack',
    weight: 4,
    isavailable: true,
  ),
];
